# Generated by Django 5.2.5 on 2025-10-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_username_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_level',
            field=models.IntegerField(choices=[(0, 'Usuário Comum'), (1, 'Funcionário'), (2, 'Administrador')], default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.URLField(blank=True, help_text='URL para foto do perfil'),
        ),
    ]
