# Generated by Django 5.2.5 on 2025-10-03 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=50)),
                ('plan_image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_seen', 'Não Visto'), ('open', 'Em Aberto'), ('closed', 'Fechado')], default='not_seen', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['start_datetime']},
        ),
        migrations.AlterModelOptions(
            name='spacetype',
            options={'ordering': ['type']},
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='spaces_rese_space_i_b8450d_idx',
        ),
        migrations.RemoveIndex(
            model_name='reservation',
            name='spaces_rese_user_id_1729f3_idx',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='end_time',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='start_time',
            new_name='start_datetime',
        ),
        migrations.RemoveField(
            model_name='building',
            name='description',
        ),
        migrations.RemoveField(
            model_name='space',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='space',
            name='description',
        ),
        migrations.RemoveField(
            model_name='space',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='spacetype',
            name='name',
        ),
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.building'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='location_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='location_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spacetype',
            name='type',
            field=models.CharField(default='Sala Padrão', max_length=90),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.CharField(max_length=1400),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.space'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('canceled', 'Cancelado'), ('completed', 'Concluído'), ('in_progress', 'Em Andamento')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='space',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.building'),
        ),
        migrations.AlterField(
            model_name='space',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='space',
            name='name',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='space',
            name='space_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.spacetype'),
        ),
        migrations.AlterField(
            model_name='spacetype',
            name='description',
            field=models.CharField(default='Descrição padrão', max_length=500),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['space', 'start_datetime', 'end_datetime'], name='spaces_rese_space_i_9250f5_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'start_datetime'], name='spaces_rese_user_id_e72ea9_idx'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='spaces.building'),
        ),
        migrations.AddField(
            model_name='space',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.floorplan'),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.reservation'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='floorplan',
            unique_together={('building', 'floor_name')},
        ),
    ]
