# Generated by Django 5.2.5 on 2025-10-10 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_floorplan_notification_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='floorplan',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='plan_image_url',
            field=models.URLField(blank=True, help_text='URL externa da imagem', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.building'),
        ),
        migrations.RemoveField(
            model_name='floorplan',
            name='plan_image',
        ),
    ]
