# Generated by Django 5.2.5 on 2025-10-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_alter_floorplan_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorplan',
            name='plan_image',
            field=models.ImageField(blank=True, help_text='Upload da imagem da planta', null=True, upload_to='floor_plans/'),
        ),
        migrations.AlterField(
            model_name='floorplan',
            name='plan_image_url',
            field=models.URLField(blank=True, help_text='URL externa da imagem (opcional)', max_length=500, null=True),
        ),
    ]
