# Generated by Django 5.2.5 on 2025-10-10 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0004_floorplan_plan_image_alter_floorplan_plan_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.floorplan'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.building'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.space'),
        ),
    ]
